### ISSUE TITLE
Doesn't work at all on Mate8 android 6 rooted

### ISSUE THREAD

**Issue by DerAlSem** [eladnava/shutapp-android#2]
What can i provide you for further investigation?

**Comment by eladnava** [comment]
Hi @DerAlSem,
Please provide the entire device logcat after installing ShutApp.

Did you follow the Usage section in the README to the letter?

**Comment by DerAlSem** [comment]
I've totally missed the 6th point!

Rechecking now, will be back shortly.

**Comment by DerAlSem** [comment]
You definitely need to mark the 6th point with red bold or smth similiar.

Works like a charm. Brilliant work!

**Comment by DerAlSem** [comment]
Weird, seems it doesn't work again... 
I see notification in the top and counter continues...

**Comment by eladnava** [comment]
Please provide the device logcat.

**Comment by eladnava** [comment]
Closing due to lack of reply.
