### ISSUE TITLE
Not working on my Moto G4 Plus.

### ISSUE THREAD

**Issue by reeshabhranjan** [eladnava/shutapp-android#3]
I am using Lineage OS 14.1 based on Android 7.1.1. The app simple doesn't works.

**Comment by eladnava** [comment]
Did you do configure all of your muted groups to display notifications when muted? This is what invokes ShutApp to run and mark them as read.

**Comment by reeshabhranjan** [comment]
Yes. I have tried both ways. Not working.

**Comment by eladnava** [comment]
Can you please provide your device logcat after receiving a notification from a muted group?

You can send it to me by [mail](https://eladnava.com/contact/) if you'd like. Thanks!

**Comment by reeshabhranjan** [comment]
I have never submitted a logcat before.

**Comment by eladnava** [comment]
Please follow this guide to install adb:
http://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378

Then, do the following:

1. Enable [Developer Mode](http://www.greenbot.com/article/2457986/how-to-enable-developer-options-on-your-android-phone-or-tablet.html)
2. Enable USB Debugging in Developer Options
3. Connect your device to your computer via USB cable
4. If the "Trust this computer" dialog appears, click "Yes"
5. Open a terminal in your computer
6. Run `adb logcat -d > logcat.txt`
7. Send `logcat.txt` to my e-mail

Thanks!

**Comment by reeshabhranjan** [comment]
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Minimal ADB and Fastboot>adb devices
List of devices attached
ZY223FB3SK      device


C:\Program Files (x86)\Minimal ADB and Fastboot>adb logcat -d > logcat.txt
Access is denied.

C:\Program Files (x86)\Minimal ADB and Fastboot>adb root

C:\Program Files (x86)\Minimal ADB and Fastboot>adb devices
List of devices attached
ZY223FB3SK      device


C:\Program Files (x86)\Minimal ADB and Fastboot>adb logcat -d > logcat.txt
Access is denied.

C:\Program Files (x86)\Minimal ADB and Fastboot>adb logcat > whatsapp.txt
Access is denied.

C:\Program Files (x86)\Minimal ADB and Fastboot>
```

However, adb logcat command gives a never ending huge list of sentences.

**Comment by eladnava** [comment]
Looks like you don't have write access to that directory, simply change to your desktop and run it from there. Make sure `adb` is in your path.

**Comment by reeshabhranjan** [comment]
Well I have some exams coming in whole of March. Will contact you again in the first week of April.

**Comment by reeshabhranjan** [comment]
Hello again!

**Comment by eladnava** [comment]
@reeshabhkumarranjan Hi!

Please follow these instructions to provide your logcat so we can debug this issue:
https://github.com/eladnava/shutapp-android/issues/3#issuecomment-280607319

**Comment by reeshabhranjan** [comment]
Hello. Unfortunately, fastboot devices command shows nothing, but adb devices does. I even permitted my PC for USB debugging.

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
There is no need to run `fastboot devices`. Please run the following to extract the device logcat (after running ShutApp and having it fail to mute a WhatsApp group chat):

1. Open a terminal in your computer
2. Run `adb logcat -d > logcat.txt`
3. Send `logcat.txt` to my e-mail

**Comment by reeshabhranjan** [comment]
Ah okay. Will try to do it by today, otherwise tomorrow.

**Comment by reeshabhranjan** [comment]
Check your inbox. Sorry for sending two times. Consider the latest mail.

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
The exception being thrown is as follows:

```
07-31 18:00:22.986 15343 15343 E ShutApp : Handle notification failed
07-31 18:00:22.986 15343 15343 E ShutApp : java.io.FileNotFoundException: /data/data/com.eladnava.shutapp/files/sqlite3 (No such file or directory)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at java.io.FileOutputStream.open(Native Method)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.util.DB.installBinary(DB.java:177)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.util.DB.installBinaries(DB.java:158)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.util.DB.select(DB.java:75)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.logic.NotificationHandler.getJidBySubject(NotificationHandler.java:182)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.logic.NotificationHandler.getNotificationJid(NotificationHandler.java:125)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.logic.NotificationHandler.handleWhatsAppNotification(NotificationHandler.java:42)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.eladnava.shutapp.listeners.NotificationListener.onNotificationPosted(NotificationListener.java:28)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:237)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1498)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at android.os.Looper.loop(Looper.java:153)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at android.app.ActivityThread.main(ActivityThread.java:6240)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at java.lang.reflect.Method.invoke(Native Method)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
07-31 18:00:22.986 15343 15343 E ShutApp : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

This exception means that the app was not able to copy the `sqlite3` binary to `/data/data/com.eladnava.shutapp/files/sqlite3`. 

According to [this](https://stackoverflow.com/a/1998541/1123355), the app should be modified to use `Context.getFilesDir()` instead of hard-coding `/data/data/`.

Will get around to it in a few days.

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
I have made the necessary changes, please clone the repository and run the new version of the application on your device and let me know if it works now! 🎉 

If it works, I will update the APK as well.

**Comment by reeshabhranjan** [comment]
I am new here and I don't know how to clone the repository and install the apk on my device. 

__Update__ 
Do I need to download the ~~file~~ folder and use the apk from there? 

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
Please download the APK from here:
https://github.com/eladnava/shutapp-android/blob/master/app/app-release.apk?raw=true

Click this link from your phone and install it when prompted. Let me know if it works! 👍

**Comment by reeshabhranjan** [comment]
Hey! It works now! But sadly, when I am using WhatsApp and then an unwanted message arrives (which is to be detected by ShutApp), then WhatsApp closes. It is inconvenient as people in that unwanted/spammed group keep on texting throughout the day. Leaving it is not an option for some obvious reasons.

Check your inbox. I have sent a logcat for the same.

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
I think the best solution in this case would be for us to check whether WhatsApp is currently in the foreground, and if so, avoid force closing it (so that the notification disappears).

What do you think?

**Comment by reeshabhranjan** [comment]
Hello. I really don't consider myself much knowledgeable to give you a suggestion. I am just here to report bugs for now :)

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eladnava** [comment]
@reeshabhkumarranjan ShutApp will no longer kill WhatsApp if it is in foreground.

Please re-download the APK from here:
https://github.com/eladnava/shutapp-android/blob/master/app/app-release.apk?raw=true

Let me know if it works.

**Comment by reeshabhranjan** [comment]
Hello. Now the app is not working as well as it is force closing too. The logcat may not contain the crashing part but I did face some crashes.

#Update: I have sent the logcat. Check your inbox.

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,

There appear to be two issues:
1) Root access is not provided to ShutApp on a consistent basis:

```
08-11 21:03:42.727 21337 21337 E ShutApp : java.lang.Exception: You must provide root access to ShutApp.
08-11 21:03:42.727 21337 21337 E ShutApp : 
08-11 21:03:42.727 21337 21337 E ShutApp : Please open the SuperSU app and grant root access to ShutApp.
```

Please open the SuperSU app and delete access for ShutApp. Then, reopen ShutApp and untick the "Ask again" box while granting root permissions to the app.

2) There appears to be a bug in ShutApp:

```
08-11 21:04:47.403 21337 21337 E ShutApp : Handle notification failed
08-11 21:04:47.403 21337 21337 E ShutApp : java.lang.NumberFormatException: For input string: ""
08-11 21:04:47.403 21337 21337 E ShutApp : 	at java.lang.Long.parseLong(Long.java:455)
08-11 21:04:47.403 21337 21337 E ShutApp : 	at java.lang.Long.parseLong(Long.java:485)
08-11 21:04:47.403 21337 21337 E ShutApp : 	at com.eladnava.shutapp.logic.NotificationHandler.isJidMuted(NotificationHandler.java:259)
```

This issue has now been resolved, please re-download the APK from here:
https://github.com/eladnava/shutapp-android/blob/master/app/app-release.apk?raw=true

Good luck!

**Comment by reeshabhranjan** [comment]
Now the FC issue is not there but ShutApp works like around 2 out of 5 times. Logcat_4 is there in your inbox.

**Comment by eladnava** [comment]
Hi @reeshabhkumarranjan,
Thanks for your help.

The logs indicate that ShutApp is not being granted root access by your phone sometimes.

```
08-12 14:45:35.801  4251  4251 E ShutApp : Handle notification failed
08-12 14:45:35.801  4251  4251 E ShutApp : java.lang.Exception: You must provide root access to ShutApp.
```

Is it possible that your phone is not correctly rooted? Do you have any other root-enabled apps that are working as expected in the background?

**Comment by reeshabhranjan** [comment]
Well, I sent you another logcat_5 before I saw your reply above. That was for force closing, which I observed just now. I have only built-in root service for now.

**Comment by reeshabhranjan** [comment]
Can you suggest an app which will give report on the functioning of the root access? By the way I have Greenify enabled right now.

**Comment by eladnava** [comment]
Greenify might have something to do with it -- can you please try disabling it?

**Comment by reeshabhranjan** [comment]
Damn, I just found my way around this conversation. It has been a while haha. I wasn't able to provide you any further logs hahaha, got way too busy.
