### ISSUE TITLE
Not working on Moto G1 Neugat

### ISSUE THREAD

**Issue by lonnrot** [eladnava/shutapp-android#4]
So far It won't work on my Rooted Moto G1 Nougat, the App was installed directly on the phone (without the USB commands), checked all permissions and messages keep pilling up on the top.

**Comment by eladnava** [comment]
Hi @lonnrot,
Have you configured all of your muted groups to display notifications when muted within WhatsApp?

**Comment by lonnrot** [comment]
Yes, but I have disabled WhatsApp notifications in the Applications Manager
menu. Can this affect it?

**Comment by eladnava** [comment]
Yes, that would explain the behavior.

This app only runs when a new WhatsApp notification is posted to the notification tray.

**Comment by eladnava** [comment]
Closing due to lack of response. Reopen if necessary.
